// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInYXjKjxvf2rxEqJ2Cw3QJPBsDCQlZb8',
    appId: '1:575153932972:web:9c7c7014e7e7436b402d09',
    messagingSenderId: '575153932972',
    projectId: 'example-7f085',
    authDomain: 'example-7f085.firebaseapp.com',
    storageBucket: 'example-7f085.appspot.com',
    measurementId: 'G-JB2CCXFSME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspRn8_T0M1y_jC-ZPdfnzp4Z9TDJe-og',
    appId: '1:575153932972:android:0894934b2035bc51402d09',
    messagingSenderId: '575153932972',
    projectId: 'example-7f085',
    storageBucket: 'example-7f085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1Ke4lT9OBLFCoTzLYZARxeOHuIFaorE',
    appId: '1:575153932972:ios:aca5dc9a4e6c7310402d09',
    messagingSenderId: '575153932972',
    projectId: 'example-7f085',
    storageBucket: 'example-7f085.appspot.com',
    iosClientId: '575153932972-73bljjnqbk1am8v7f9108k4ocdj24jlf.apps.googleusercontent.com',
    iosBundleId: 'com.tuantq.test.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1Ke4lT9OBLFCoTzLYZARxeOHuIFaorE',
    appId: '1:575153932972:ios:88065ec683fffaf5402d09',
    messagingSenderId: '575153932972',
    projectId: 'example-7f085',
    storageBucket: 'example-7f085.appspot.com',
    iosClientId: '575153932972-11fj52rtgbqg37v6rg503mnopjoo556k.apps.googleusercontent.com',
    iosBundleId: 'com.tuantq.test.testfirebase.RunnerTests',
  );
}
